on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.19.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Use cache for Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # See https://github.com/gobuffalo/.github/issues/2
      - name: Run tests (on Windows, w/out -race)
        if: ${{ matrix.os == 'windows-latest' }}
        run: go test ./...
      - name: Run tests (on Linux/MacOS, w/ -race)
        if: ${{ matrix.os != 'windows-latest' }}
        run: go test -race ./...